const $=s=>document.querySelector(s);
function webglOK(){try{const c=document.createElement('canvas');return !!(window.WebGLRenderingContext&&(c.getContext('webgl')||c.getContext('experimental-webgl')))}catch{return false}}
if(!webglOK()||typeof Globe!=='function'){document.querySelector('#fallback')?.classList.remove('hidden');document.querySelector('#status').textContent='3D UNAVAILABLE';throw new Error('WebGL unavailable')}
const statusEl=$('#status'),card=$('#card'),body=$('#cardBody'),clock=$('#clock'),legend=$('#legend'),hero=$('#hero'),slider=$('#time'),timeLabel=$('#timeLabel');
const labels={quake:'QUAKES',wildfire:'FIRES',storm:'STORMS',volcano:'VOLCANOES',iceberg:'ICE',dust:'DUST',neo:'NEAR-EARTH'},colors={quake:'#fff',wildfire:'#ff7043',storm:'#66c7ff',volcano:'#ffc857',iceberg:'#bdefff',dust:'#d7b27c',neo:'#c994ff'};
function normalizeEvent(d){const source=typeof d.source==='object'&&d.source?d.source:{name:d.source||'UNKNOWN',url:d.url||''};return {...d,source:source.name||'UNKNOWN',url:d.url||source.url||'',time:Number(d.time??d.observed_at)||null,lat:Number(d.lat),lng:Number(d.lng),mag:Number(d.mag)||0,depth:Number(d.depth)||0}}
const globe=Globe()($('#globe')).backgroundColor('#020408').globeImageUrl('https://unpkg.com/three-globe/example/img/earth-night.jpg').bumpImageUrl('https://unpkg.com/three-globe/example/img/earth-topology.png').showAtmosphere(true).atmosphereColor('#6f8fa8').atmosphereAltitude(.16).pointLat('lat').pointLng('lng').pointAltitude(d=>d.kind==='neo'?.18:d.kind==='quake'?Math.max(.012,(d.mag||0)*.008):.025).pointRadius(d=>d.kind==='neo'?.09:d.kind==='quake'?Math.max(.05,(d.mag||0)*.035):.13).pointColor(d=>colors[d.kind]).pointLabel(d=>'<b>'+labels[d.kind]+'</b><br>'+safe(d.title)).ringsData([]).ringLat('lat').ringLng('lng').ringColor(d=>()=>colors[d.kind]).ringMaxRadius(d=>d.kind==='quake'?Math.max(.6,(d.mag||0)*.32):1.15).ringPropagationSpeed(.7).ringRepeatPeriod(1500).onPointClick(fly);
globe.controls().autoRotate=true;globe.controls().autoRotateSpeed=.16;globe.pointOfView({lat:18,lng:-25,altitude:2.15});
let all=[],enabled=new Set(Object.keys(labels)),fails=[],viewTime=Date.now(),atNow=true,playing=false,playTimer=null;
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const age=(t,base=viewTime)=>{if(!t)return'AGE NOT SUPPLIED';const m=Math.max(0,Math.floor((base-t)/60000));return m<60?m+' MIN AGO':m<1440?Math.floor(m/60)+'H '+m%60+'M AGO':Math.floor(m/1440)+'D AGO'};
function visible(){const start=viewTime-24*3600000;return all.filter(d=>enabled.has(d.kind)&&(d.kind==='neo'?Math.abs(d.time-viewTime)<24*3600000:(!d.time||d.time>=start&&d.time<=viewTime)))}
function render(){const raw=visible();const MAX_POINTS=1800;const shown=raw.length<=MAX_POINTS?raw:[...raw].sort((a,b)=>score(b)-score(a)).slice(0,MAX_POINTS);globe.pointsData(shown);globe.ringsData(shown.filter(d=>(d.kind==='quake'&&d.mag>=4.5)||d.kind==='storm'));const c={};shown.forEach(d=>c[d.kind]=(c[d.kind]||0)+1);legend.textContent=Object.keys(labels).filter(k=>enabled.has(k)).map(k=>labels[k]+' '+(c[k]||0)).join(' · ')||'ALL LAYERS HIDDEN';statusEl.textContent=raw.length+' OBSERVATIONS'+(raw.length>shown.length?' · '+shown.length+' RENDERED':'')+' · '+(atNow?'NOW':'HISTORICAL WINDOW')+(fails.length?' · DEGRADED':'')}
function show(d){card.classList.remove('hidden');hero.classList.add('dim');const metric=d.kind==='quake'?'M '+d.mag.toFixed(1):labels[d.kind];body.innerHTML='<div class="kind">'+labels[d.kind]+' · '+safe(d.source)+'</div><div class="mag">'+metric+'</div><h2>'+safe(d.title)+'</h2><p>'+(d.kind==='quake'?'DEPTH '+d.depth.toFixed(1)+' KM<br>':'')+(d.detail?safe(d.detail)+'<br>':'')+age(d.time)+'<br>OBSERVED '+(d.time?new Date(d.time).toLocaleString():'timestamp not supplied')+'<br>'+d.lat.toFixed(2)+'°, '+d.lng.toFixed(2)+'°'+(d.kind==='neo'?'<br><br>VISUALIZATION ANCHOR — NOT AN EARTH-SURFACE POSITION':'')+'</p>'+(d.url?'<a href="'+safe(d.url)+'" target="_blank" rel="noreferrer">OPEN SOURCE ↗</a>':'')}
function fly(d){globe.controls().autoRotate=false;globe.pointOfView({lat:d.lat,lng:d.lng,altitude:d.kind==='neo'?1.25:.82},1300);show(d)}
function reset(){card.classList.add('hidden');hero.classList.remove('dim');globe.controls().autoRotate=true;globe.pointOfView({lat:18,lng:-25,altitude:2.15},1100)}
async function quakes(){const r=await fetch('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_week.geojson',{cache:'no-store'});if(!r.ok)throw Error();const j=await r.json();return j.features.map(f=>({kind:'quake',lat:f.geometry.coordinates[1],lng:f.geometry.coordinates[0],depth:f.geometry.coordinates[2],mag:Number(f.properties.mag)||0,title:f.properties.place||'Earthquake',time:f.properties.time,source:'USGS',url:f.properties.url||''}))}
function ek(c){const s=c.map(x=>x.id+' '+x.title).join(' ').toLowerCase();if(s.includes('wildfire'))return'wildfire';if(s.includes('storm'))return'storm';if(s.includes('volcano'))return'volcano';if(s.includes('iceberg'))return'iceberg';if(s.includes('dust'))return'dust';return null}
async function eonet(){const r=await fetch('https://eonet.gsfc.nasa.gov/api/v3/events?status=all&days=7&limit=500',{cache:'no-store'});if(!r.ok)throw Error();const j=await r.json();return j.events.flatMap(e=>{const kind=ek(e.categories||[]);if(!kind)return[];return(e.geometry||[]).flatMap(g=>{const c=g.coordinates;if(g.type!=='Point'||!Array.isArray(c))return[];return[{kind,lat:c[1],lng:c[0],title:e.title||'Natural event',time:Date.parse(g.date)||null,source:'NASA EONET',url:e.link||''}]})})}
async function neo(){const r=await fetch('https://ssd-api.jpl.nasa.gov/cad.api?dist-max=10LD&date-min=-7&date-max=%2B7&sort=date',{cache:'no-store'});if(!r.ok)throw Error();const j=await r.json(),ix=Object.fromEntries(j.fields.map((f,i)=>[f,i]));return(j.data||[]).slice(0,80).map((row,i)=>{const dist=Number(row[ix.dist]),v=Number(row[ix.v_rel]),seed=[...String(row[ix.des]||i)].reduce((a,c)=>a+c.charCodeAt(0),0);return{kind:'neo',lat:-55+(seed*37)%110,lng:-180+(seed*83)%360,title:(row[ix.des]||'Object')+' close approach',time:Date.parse(String(row[ix.cd]).replace(' ','T')+'Z')||null,source:'NASA/JPL CNEOS',detail:(Number.isFinite(dist)?dist.toFixed(2)+' LD':'')+(Number.isFinite(v)?' · '+v.toFixed(1)+' km/s':''),url:'https://cneos.jpl.nasa.gov/ca/'}})}
async function archiveSnapshot(target){try{const r=await fetch('dynamic/archive/index.json?'+Date.now(),{cache:'no-store'});if(!r.ok)throw Error();const m=await r.json(),xs=m.snapshots||[];if(!xs.length)throw Error();const pick=xs.reduce((best,x)=>Math.abs(Date.parse(x.at)-target)<Math.abs(Date.parse(best.at)-target)?x:best,xs[0]);const archivePath=pick.path.startsWith('dynamic/')?pick.path:'dynamic/'+pick.path.replace(/^\/+/, '');const s=await fetch(archivePath+'?'+Date.now(),{cache:'no-store'});if(!s.ok)throw Error();return await s.json()}catch{return null}}
async function dynamicSnapshot(){const r=await fetch('dynamic/latest.json?'+Date.now(),{cache:'no-store'});if(!r.ok)throw Error();const j=await r.json();if(!j.generated_at||!Array.isArray(j.events)||!j.events.length)throw Error();return j}
async function load(){statusEl.textContent='SYNCING EARTH + SPACE…';let base=[];let dynamic=false;try{const snap=await dynamicSnapshot();base=snap.events;dynamic=true}catch(e){}const rs=await Promise.allSettled([...(dynamic?[]:[quakes(),eonet()]),neo()]);fails=rs.filter(x=>x.status==='rejected');all=[...base,...rs.flatMap(x=>x.status==='fulfilled'?x.value:[])].map(normalizeEvent).filter(d=>Number.isFinite(d.lat)&&Number.isFinite(d.lng));if(atNow)viewTime=Date.now();render();if(dynamic)statusEl.textContent+=' · ARCHIVED ENGINE'}
document.querySelectorAll('.layer').forEach(b=>b.onclick=()=>{const k=b.dataset.layer;enabled.has(k)?enabled.delete(k):enabled.add(k);b.classList.toggle('active',enabled.has(k));render()});
slider.oninput=async()=>{const h=168-Number(slider.value);atNow=h===0;viewTime=Date.now()-h*3600000;timeLabel.textContent=atNow?'NOW':h<24?h+'H AGO':(h/24).toFixed(h%24?1:0)+'D AGO';if(!atNow){const snap=await archiveSnapshot(viewTime);if(snap&&Array.isArray(snap.events)&&snap.events.length){const neos=all.filter(x=>x.kind==='neo');all=[...snap.events.map(normalizeEvent),...neos];statusEl.dataset.archive='1'}}render()};
$('#play').onclick=()=>{playing=!playing;$('#play').textContent=playing?'PAUSE':'PLAY EARTH';if(playTimer)clearInterval(playTimer);if(playing){if(Number(slider.value)>=168)slider.value=0;slider.oninput();playTimer=setInterval(()=>{let v=Number(slider.value)+1;if(v>168){playing=false;clearInterval(playTimer);$('#play').textContent='PLAY EARTH';return}slider.value=v;slider.oninput()},250)}};$('#now').onclick=()=>{playing=false;if(playTimer)clearInterval(playTimer);$('#play').textContent='PLAY EARTH';slider.value=168;slider.oninput()};$('#random').onclick=()=>{const p=visible();if(!p.length)return;const ranked=[...p].sort((a,b)=>score(b)-score(a)).slice(0,60);fly(ranked[Math.floor(Math.random()*ranked.length)])};function score(d){return(d.kind==='quake'?(d.mag||0)*2:5)+(d.time?Math.max(0,3-Math.abs(viewTime-d.time)/86400000):0)}
$('#reset').onclick=reset;$('#closeCard').onclick=()=>{card.classList.add('hidden');hero.classList.remove('dim')};window.addEventListener('keydown',e=>{if(e.key==='Escape')reset();if(e.key.toLowerCase()==='r')$('#random').click()});setInterval(()=>{clock.textContent=new Date().toISOString().replace('T',' · ').slice(0,21)+' UTC';if(atNow){viewTime=Date.now();render()}},60000);clock.textContent=new Date().toISOString().replace('T',' · ').slice(0,21)+' UTC';load();setInterval(load,300000);