const $=s=>document.querySelector(s),statusEl=$('#status'),card=$('#card'),cardBody=$('#cardBody'),clock=$('#clock'),legend=$('#legend'),hero=$('#hero');
const labels={quake:'QUAKES',wildfire:'FIRES',storm:'STORMS',volcano:'VOLCANOES',iceberg:'ICE',dust:'DUST',neo:'NEAR-EARTH'},colors={quake:'#fff',wildfire:'#ff7043',storm:'#66c7ff',volcano:'#ffc857',iceberg:'#bdefff',dust:'#d7b27c',neo:'#c994ff'};
const globe=Globe()($('#globe')).backgroundColor('#020408').globeImageUrl('https://unpkg.com/three-globe/example/img/earth-night.jpg').bumpImageUrl('https://unpkg.com/three-globe/example/img/earth-topology.png').showAtmosphere(true).atmosphereColor('#6f8fa8').atmosphereAltitude(.16).pointLat('lat').pointLng('lng').pointAltitude(d=>d.kind==='neo'?.18:d.kind==='quake'?Math.max(.012,(d.mag||0)*.008):.025).pointRadius(d=>d.kind==='neo'?.09:d.kind==='quake'?Math.max(.05,(d.mag||0)*.035):.13).pointColor(d=>colors[d.kind]).pointLabel(d=>'<b>'+labels[d.kind]+'</b><br>'+safe(d.title)).ringsData([]).ringLat('lat').ringLng('lng').ringColor(d=>()=>colors[d.kind]).ringMaxRadius(d=>d.kind==='quake'?Math.max(.6,(d.mag||0)*.32):1.15).ringPropagationSpeed(.7).ringRepeatPeriod(1500).onPointClick(flyTo);
globe.controls().autoRotate=true;globe.controls().autoRotateSpeed=.16;globe.controls().enableDamping=true;globe.controls().dampingFactor=.08;globe.pointOfView({lat:18,lng:-25,altitude:2.15});
let all=[],enabled=new Set(Object.keys(labels)),failures=[];
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const age=t=>{if(!t)return'AGE NOT SUPPLIED';const m=Math.max(0,Math.floor((Date.now()-t)/60000));return m<60?m+' MIN AGO':m<1440?Math.floor(m/60)+'H '+m%60+'M AGO':Math.floor(m/1440)+'D AGO'};
const visible=()=>all.filter(d=>enabled.has(d.kind));
function render(){const shown=visible();globe.pointsData(shown);globe.ringsData(shown.filter(d=>(d.kind==='quake'&&d.mag>=4.5)||d.kind==='storm'));const counts={};shown.forEach(d=>counts[d.kind]=(counts[d.kind]||0)+1);legend.textContent=Object.keys(labels).filter(k=>enabled.has(k)).map(k=>labels[k]+' '+(counts[k]||0)).join(' · ')||'ALL LAYERS HIDDEN';statusEl.textContent=shown.length+' OBSERVATIONS · '+(failures.length?'DEGRADED · ':'')+'EARTH + NEAR-EARTH SPACE'}
function show(d){card.classList.remove('hidden');hero.classList.add('dim');const metric=d.kind==='quake'?'M '+d.mag.toFixed(1):labels[d.kind];cardBody.innerHTML='<div class="kind">'+labels[d.kind]+' · '+safe(d.source)+'</div><div class="mag">'+metric+'</div><h2>'+safe(d.title)+'</h2><p>'+(d.kind==='quake'?'DEPTH '+d.depth.toFixed(1)+' KM<br>':'')+(d.detail?safe(d.detail)+'<br>':'')+age(d.time)+'<br>OBSERVED '+(d.time?new Date(d.time).toLocaleString():'timestamp not supplied')+'<br>'+d.lat.toFixed(2)+'°, '+d.lng.toFixed(2)+'°</p>'+(d.url?'<a href="'+safe(d.url)+'" target="_blank" rel="noreferrer">OPEN SOURCE ↗</a>':'')}
function flyTo(d){globe.controls().autoRotate=false;globe.pointOfView({lat:d.lat,lng:d.lng,altitude:d.kind==='neo'?1.25:.82},1400);show(d)}
function reset(){card.classList.add('hidden');hero.classList.remove('dim');globe.controls().autoRotate=true;globe.pointOfView({lat:18,lng:-25,altitude:2.15},1200)}
async function quakes(){const r=await fetch('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson',{cache:'no-store'});if(!r.ok)throw Error();const j=await r.json();return j.features.map(f=>({kind:'quake',lat:f.geometry.coordinates[1],lng:f.geometry.coordinates[0],depth:f.geometry.coordinates[2],mag:Number(f.properties.mag)||0,title:f.properties.place||'Earthquake',time:f.properties.time,source:'USGS',url:f.properties.url||''}))}
function eKind(c){const s=c.map(x=>x.id+' '+x.title).join(' ').toLowerCase();if(s.includes('wildfire'))return'wildfire';if(s.includes('storm'))return'storm';if(s.includes('volcano'))return'volcano';if(s.includes('iceberg'))return'iceberg';if(s.includes('dust'))return'dust';return null}
async function eonet(){const r=await fetch('https://eonet.gsfc.nasa.gov/api/v3/events?status=open&limit=500',{cache:'no-store'});if(!r.ok)throw Error();const j=await r.json();return j.events.flatMap(e=>{const kind=eKind(e.categories||[]);if(!kind||!e.geometry?.length)return[];const g=e.geometry[e.geometry.length-1],c=g.coordinates;if(g.type!=='Point'||!Array.isArray(c)||!Number.isFinite(c[0])||!Number.isFinite(c[1]))return[];return[{kind,lat:c[1],lng:c[0],title:e.title||'Natural event',time:Date.parse(g.date)||null,source:'NASA EONET',url:e.link||''}]})}
async function neo(){const r=await fetch('https://ssd-api.jpl.nasa.gov/cad.api?dist-max=10LD&date-min=now&date-max=%2B7&sort=date',{cache:'no-store'});if(!r.ok)throw Error();const j=await r.json(),ix=Object.fromEntries(j.fields.map((f,i)=>[f,i]));return(j.data||[]).slice(0,40).map((row,i)=>{const dist=Number(row[ix.dist]),v=Number(row[ix.v_rel]);const seed=[...String(row[ix.des]||i)].reduce((a,c)=>a+c.charCodeAt(0),0);return{kind:'neo',lat:-55+(seed*37)%110,lng:-180+(seed*83)%360,title:(row[ix.des]||'Object')+' close approach',time:Date.parse(String(row[ix.cd]).replace(' ','T')+'Z')||null,source:'NASA/JPL CNEOS',detail:(Number.isFinite(dist)?dist.toFixed(2)+' LD':'distance n/a')+(Number.isFinite(v)?' · '+v.toFixed(1)+' km/s':''),url:'https://cneos.jpl.nasa.gov/ca/'}})}
async function load(){statusEl.textContent='SYNCING EARTH + SPACE…';const rs=await Promise.allSettled([quakes(),eonet(),neo()]);failures=rs.filter(r=>r.status==='rejected');all=rs.flatMap(r=>r.status==='fulfilled'?r.value:[]).filter(d=>Number.isFinite(d.lat)&&Number.isFinite(d.lng));render()}
document.querySelectorAll('.layer').forEach(b=>b.onclick=()=>{const k=b.dataset.layer;enabled.has(k)?enabled.delete(k):enabled.add(k);b.classList.toggle('active',enabled.has(k));render()});
$('#random').onclick=()=>{const pool=visible();if(!pool.length)return;const ranked=[...pool].sort((a,b)=>score(b)-score(a)).slice(0,Math.min(60,pool.length));flyTo(ranked[Math.floor(Math.random()*ranked.length)])};
function score(d){const fresh=d.time?Math.max(0,7-Math.abs(Date.now()-d.time)/86400000):0;return(d.kind==='quake'?(d.mag||0)*2:5)+fresh}
$('#reset').onclick=reset;$('#closeCard').onclick=()=>{card.classList.add('hidden');hero.classList.remove('dim')};window.addEventListener('keydown',e=>{if(e.key==='Escape')reset();if(e.key.toLowerCase()==='r')$('#random').click()});setInterval(()=>clock.textContent=new Date().toISOString().replace('T',' · ').slice(0,21)+' UTC',1000);load();setInterval(load,300000);